
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-2
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"InstructorSearchBackend","number":13,"title":"Add Instructor Search Backend","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/13"},{"author":{"id":"U_kgDOBbLB7w","is_bot":false,"login":"maya-maye","name":""},"headRefName":"mm-CreateInstructorPage","number":12,"title":"mm-CreateSBIPage","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/12"},{"author":{"id":"MDQ6VXNlcjY0Mzg1Mzgw","is_bot":false,"login":"justinthecao","name":"Justin Cao"},"headRefName":"jc-menu-search-option","number":11,"title":"added the professor menu option","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/11"},{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"Arik-CourseByInstructorSearchForm","number":10,"title":"Add course by instructor search form","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/10"},{"author":{"id":"MDQ6VXNlcjcyODQyMzEy","is_bot":false,"login":"JNewman-cell","name":"Jackson Newman"},"headRefName":"jn-AppNavbarColorChange","number":7,"title":"Jn app navbar color change","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/7"}]
