
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-2
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"Arik-CourseByInstructorControllerChanges","number":36,"title":"Revamp Course By Instructor Backend","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/36"},{"author":{"id":"MDQ6VXNlcjY0Mzg1Mzgw","is_bot":false,"login":"justinthecao","name":"Justin Cao"},"headRefName":"nh-searchBar","number":34,"title":"Nh search bar","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"nh-searchBar-pc-office-hours","number":32,"title":"pc/nh - work in progress from office hours","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/32"},{"author":{"id":"MDQ6VXNlcjcyODQyMzEy","is_bot":false,"login":"JNewman-cell","name":"Jackson Newman"},"headRefName":"jn-AddCheckboxInstructorForm","number":31,"title":"Add checkbox instructor form","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/31"},{"author":{"id":"U_kgDOBXu4sA","is_bot":false,"login":"ColinBaylis","name":""},"headRefName":"CB-CompleteCompactNavbar","number":29,"title":"Cb complete compact navbar","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/29"},{"author":{"id":"U_kgDOBbLB7w","is_bot":false,"login":"maya-maye","name":""},"headRefName":"mm-CreateInstructorPage","number":12,"title":"mm-CreateSBIPage","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/12"},{"author":{"id":"MDQ6VXNlcjY0Mzg1Mzgw","is_bot":false,"login":"justinthecao","name":"Justin Cao"},"headRefName":"jc-menu-search-option","number":11,"title":"added the professor menu option","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/11"}]
